version: "3.8"
services:
  facebook:
    image: 327921414325.dkr.ecr.us-west-2.amazonaws.com/ddc-relay:${VERSION}
    container_name: ddc-relay
    entrypoint: /go/bin/ddc-relay  # disable panic-monitor
    command: run
    ports:
      - "6116:6116"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

volumes:
  prometheus_data:
